### ISSUE TITLE
False-Positive ( APT_Backdoor_Win_DShell_2.yar )

### ISSUE THREAD

**Issue by lotusexpeditor** [fireeye/red_team_tool_countermeasures#12] opened 2020-12-10 02:09 UTC
It looks like this rule matches with D compiler. Some vendors started flagging with relying on this yara rule;

https://www.virustotal.com/gui/file/a022820a62198fa3e3b89749b38db1cc3a09136524682fb99a3ce36652725065/details

https://github.com/fireeye/red_team_tool_countermeasures/blob/ac479ae150e1541445023952f569b7ca0d190b7b/rules/DSHELL/supplemental/yara/APT_Backdoor_Win_DShell_2.yar

**Comment by williballenthin** [comment] 2020-12-10 04:02
to save people a click:
![image](https://user-images.githubusercontent.com/156560/101720055-d84b8a00-3a61-11eb-8a8c-fc9c9e102256.png)

**Comment by williballenthin** [comment] 2020-12-10 04:06
Despite the Tencent detection, I don't think this rule matches the file:

![image](https://user-images.githubusercontent.com/156560/101720092-f2856800-3a61-11eb-8082-5bd6c8f71fbc.png)

The rule should not flag `rdmd` thanks to these ignores:

![image](https://user-images.githubusercontent.com/156560/101720177-252f6080-3a62-11eb-8377-345eb59410fa.png)

Unfortunately, I don't have any insight into why Tencent flags this file nor how they've derived detections from this repository.

I'm going to close this issue because I think that the rule works as intended. If I misunderstood something, please reopen and I'm happy to discuss further.

**Closed by williballenthin** 2020-12-10 04:06 UTC

**Comment by gutterchurl** [comment] 2020-12-18 20:17
This does have a FP matching the open source project https://github.com/CyberShadow/dhcptest

> APT_Backdoor_Win_DShell_2 ../c32514711f72002e9a540c2434dee7b239485d01a95a7530b939fed43f277f6d
0x8295:$dlang6: \..\..\src\phobos\std\utf.d
0x606d:$dlang8: \..\..\src\phobos\std\format.d
0x67c1:$dlang8: \..\..\src\phobos\std\format.d
0x10e71:$dlang10: \..\..\src\phobos\std\stdio.d
<snipped all the $s* matches>

https://www.virustotal.com/gui/file/c32514711f72002e9a540c2434dee7b239485d01a95a7530b939fed43f277f6d/behavior/

Confirmed hash match with compiled binary linked from the github project page: http://files.thecybershadow.net/dhcptest/old/dhcptest-0.6-win32.exe

I have not analyzed the dhcptest program to determine how the rule may be modified, but wanted to make you aware.

**Comment by recvfrom** [comment] 2020-12-21 17:26
a022820a62198fa3e3b89749b38db1cc3a09136524682fb99a3ce36652725065 is listed in https://github.com/fireeye/red_team_tool_countermeasures/blob/master/all-hashes.csv - Is that a mistake?
